language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - python setup.py -q install
script: nosetests -s -v --with-coverage --cover-package=pyplyr --cover-branches --cover-html
cache: pip
